import { defineConfig } from 'oxfmt'

export default defineConfig({
  useTabs: false,
  tabWidth: 2,
  printWidth: 100,
  singleQuote: true,
  jsxSingleQuote: false,
  quoteProps: 'as-needed',
  trailingComma: 'all',
  semi: false,
  arrowParens: 'always',
  bracketSameLine: false,
  bracketSpacing: true,
  endOfLine: 'lf',
  sortImports: {
    newlinesBetween: false,
  },
  sortPackageJson: true,
  // CHANGELOG.md files are generated by Changesets; formatting them only creates churn.
  ignorePatterns: [
    '.agents/**',
    '.cursor/**',
    '**/dist/**',
    '**/routeTree.gen.ts',
    '**/CHANGELOG.md',
  ],
})
